### ISSUE TITLE
Please check the screenshot error

### ISSUE THREAD

**Issue by nk932714** [rakshans1/docstash#2]
![image](https://user-images.githubusercontent.com/29853208/29156213-4e6332ec-7dbe-11e7-9c0a-16a0942c87ce.png)

please fix this issue 

are you using Jpillora repo for torrnts

**Comment by rakshans1** [comment]
are you accessing via http://docstash.herokuapp.com ?

**Comment by nk932714** [comment]
Yes, but that error has gone now. Now am facing the new error. Please check your site it struck on a single torrent loading. i can't add new torrent also unable to remove the previous. Can you fix that issue.

One more question can you describe how to add this repository to heroku?

**Comment by nk932714** [comment]
Please Fix struck on loading status. Do you know why this error arise ?
